# Generated by Django 5.2.8 on 2026-03-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("number", models.SmallIntegerField()),
                ("max_student", models.SmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("START", "Start"), ("READY", "Ready"), ("END", "End")], default="READY", max_length=10
                    ),
                ),
            ],
            options={
                "db_table": "cohorts",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("name", models.CharField(max_length=30, unique=True)),
                ("tag", models.CharField(max_length=3, unique=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="CohortStudent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("cohort_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.cohort")),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "db_table": "cohort_students",
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="course_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.course"),
        ),
        migrations.CreateModel(
            name="EnrollmentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "status",
                    models.CharField(
                        choices=[("REJECT", "Reject"), ("PENDING", "Pending"), ("ALLOW", "Allow")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("cohort_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.cohort")),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "db_table": "enrollment_requests",
            },
        ),
        migrations.CreateModel(
            name="LearningCoach",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("course_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.course")),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "db_table": "learning_coachs",
            },
        ),
        migrations.CreateModel(
            name="OperationManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("course_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.course")),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "db_table": "operation_managers",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=30, unique=True)),
                ("number_of_days", models.SmallIntegerField()),
                ("number_of_hours", models.SmallIntegerField()),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.BooleanField(default=True)),
                ("course_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.course")),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="TrainingAssistant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("cohort_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.cohort")),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "db_table": "training_assistants",
            },
        ),
    ]
