# Generated by Django 5.2.8 on 2026-03-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PENNDING", "Pennding"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
