# Generated by Django 5.2.8 on 2026-03-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0002_alter_cohort_status_alter_enrollmentrequest_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["course_id", "number"], name="cohorts_course__85b8e4_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["course_id", "title"], name="subjects_course__d02d19_idx"),
        ),
    ]
