# Generated by Django 5.2.8 on 2026-03-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0003_cohort_cohorts_course__85b8e4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("course_id", "title")},
        ),
    ]
