# Generated by Django 5.2.8 on 2026-03-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0004_alter_subject_title_alter_subject_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cohort",
            unique_together={("course_id", "number")},
        ),
    ]
