# Generated by Django 5.2.8 on 2026-03-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_alter_cohort_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cohort",
            name="cohorts_course__85b8e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="subject",
            name="subjects_course__d02d19_idx",
        ),
        migrations.RenameField(
            model_name="cohort",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="cohortstudent",
            old_name="cohort_id",
            new_name="cohort",
        ),
        migrations.RenameField(
            model_name="cohortstudent",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="enrollmentrequest",
            old_name="cohort_id",
            new_name="cohort",
        ),
        migrations.RenameField(
            model_name="enrollmentrequest",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="learningcoach",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="learningcoach",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="operationmanager",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="operationmanager",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="trainingassistant",
            old_name="cohort_id",
            new_name="cohort",
        ),
        migrations.RenameField(
            model_name="trainingassistant",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="cohort",
            unique_together={("course", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("course", "title")},
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["course", "number"], name="cohorts_course__9f8bc7_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["course", "title"], name="subjects_course__693ae7_idx"),
        ),
    ]
