# Generated by Django 5.2.8 on 2026-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0006_remove_cohort_cohorts_course__85b8e4_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cohort",
            name="cohorts_course__9f8bc7_idx",
        ),
        migrations.RemoveIndex(
            model_name="subject",
            name="subjects_course__693ae7_idx",
        ),
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.CharField(
                choices=[("ACTIVATED", "Activated"), ("DEACTIVATED", "Deactivated")], default="ACTIVATED", max_length=15
            ),
        ),
    ]
