# Generated by Django 5.2.8 on 2026-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0006_remove_cohort_cohorts_course__85b8e4_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentrequest",
            name="cohort",
        ),
        migrations.RemoveField(
            model_name="enrollmentrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="learningcoach",
            name="course",
        ),
        migrations.RemoveField(
            model_name="learningcoach",
            name="user",
        ),
        migrations.RemoveField(
            model_name="operationmanager",
            name="course",
        ),
        migrations.RemoveField(
            model_name="operationmanager",
            name="user",
        ),
        migrations.RemoveField(
            model_name="trainingassistant",
            name="cohort",
        ),
        migrations.RemoveField(
            model_name="trainingassistant",
            name="user",
        ),
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.CharField(
                choices=[("ACTIVATED", "Activated"), ("DEACTIVATED", "Deactivated")], default="ACTIVATED", max_length=15
            ),
        ),
        migrations.DeleteModel(
            name="CohortStudent",
        ),
        migrations.DeleteModel(
            name="EnrollmentRequest",
        ),
        migrations.DeleteModel(
            name="LearningCoach",
        ),
        migrations.DeleteModel(
            name="OperationManager",
        ),
        migrations.DeleteModel(
            name="TrainingAssistant",
        ),
    ]
