# Generated by Django 5.2.8 on 2026-03-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_remove_exam_subject_remove_examdeployment_exam_and_more"),
        ("subject", "0006_remove_cohort_cohorts_course__85b8e4_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningcoach",
            name="course",
        ),
        migrations.RemoveField(
            model_name="learningcoach",
            name="user",
        ),
        migrations.RemoveField(
            model_name="operationmanager",
            name="course",
        ),
        migrations.RemoveField(
            model_name="operationmanager",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subject",
            name="course",
        ),
        migrations.RemoveField(
            model_name="trainingassistant",
            name="cohort",
        ),
        migrations.RemoveField(
            model_name="trainingassistant",
            name="user",
        ),
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="EnrollmentRequest",
        ),
        migrations.DeleteModel(
            name="LearningCoach",
        ),
        migrations.DeleteModel(
            name="OperationManager",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="TrainingAssistant",
        ),
    ]
