# Generated by Django 5.2.8 on 2026-03-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0007_remove_enrollmentrequest_cohort_and_more"),
        ("users", "0002_remove_user_is_active_user_status_alter_user_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortStudent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("cohort", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.cohort")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "db_table": "cohort_students",
            },
        ),
    ]
