# Generated by Django 5.2.8 on 2026-03-18 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0007_remove_cohort_cohorts_course__9f8bc7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PREPARING", "Preparing"), ("IN_PROGRESS", "In Progress"), ("FINISHED", "Finished")],
                default="PREPARING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="cohortstudent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cohort_students", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
