# Generated by Django 5.2.8 on 2026-03-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0008_cohortstudent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PENNDING", "Pennding"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="PENNDING",
                max_length=15,
            ),
        ),
    ]
