# Generated by Django 5.2.8 on 2026-03-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0010_enrollmentrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
