# Generated by Django 5.2.8 on 2026-03-09 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("content", models.TextField()),
                ("is_adopted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "답변",
                "db_table": "answers",
            },
        ),
        migrations.CreateModel(
            name="AnswerImages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("img_url", models.CharField(max_length=255)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="questions.answers"
                    ),
                ),
            ],
            options={
                "verbose_name": "답변 이미지",
                "db_table": "answer_images",
            },
        ),
        migrations.CreateModel(
            name="AnswerComments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="questions.answers"
                    ),
                ),
            ],
            options={
                "verbose_name": "답변 내용",
                "db_table": "answer_comments",
            },
        ),
        migrations.CreateModel(
            name="QuestionCategories",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("name", models.CharField(max_length=15)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="questions.questioncategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 카테고리",
                "db_table": "question_categories",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("view_count", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="questions.questioncategories"),
                ),
            ],
            options={
                "verbose_name": "질문",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="QuestionImages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("img_url", models.CharField(max_length=255)),
                (
                    "questions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="questions.questions"
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 이미지",
                "db_table": "question_images",
            },
        ),
        migrations.CreateModel(
            name="QuestionAiAnswers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("output", models.TextField()),
                ("using_model", models.CharField(max_length=50)),
                (
                    "questions",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ai_answers", to="questions.questions"
                    ),
                ),
            ],
            options={
                "verbose_name": "자동 질문 답변",
                "db_table": "question_ai_answers",
            },
        ),
        migrations.AddField(
            model_name="answers",
            name="questions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="questions.questions"
            ),
        ),
    ]
