# Generated by Django 5.2.8 on 2026-03-09 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotSessions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(help_text="AI가 요약한 세션 제목", max_length=30)),
                (
                    "using_model",
                    models.CharField(
                        choices=[("gemini-1.5-flash", "Gemini 1.5 Flash"), ("gemini-2.0", "Gemini 2.0")],
                        help_text="LLM 사용 모델",
                        max_length=50,
                    ),
                ),
                (
                    "questions",
                    models.ForeignKey(
                        blank=True,
                        db_column="question_id",
                        help_text="파생된 Q&A 질문 ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_sessions",
                        to="questions.questions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="채팅을 시작한 유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 세션",
                "db_table": "chatbot_sessions",
                "unique_together": {("user", "questions")},
            },
        ),
        migrations.CreateModel(
            name="ChatbotCompletions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("message", models.TextField(help_text="챗봇과의 채팅내용")),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "사용자"), ("ASSISTANT", "AI")],
                        help_text="USER(사용자) 또는 ASSISTANT(AI) 구분",
                        max_length=10,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        help_text="소속된 대화 세션 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="chatbot.chatbotsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 메시지",
                "db_table": "chatbot_completions",
            },
        ),
    ]
