# Generated by Django 5.2.8 on 2026-03-11 02:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbotsessions",
            old_name="questions",
            new_name="question",
        ),
        migrations.AlterUniqueTogether(
            name="chatbotsessions",
            unique_together={("user", "question")},
        ),
    ]
