# Generated by Django 5.2.8 on 2026-03-11 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbotsessions",
            old_name="questions",
            new_name="question",
        ),
        migrations.AlterUniqueTogether(
            name="chatbotsessions",
            unique_together={("user", "question")},
        ),
        migrations.AlterField(
            model_name="chatbotcompletions",
            name="role",
            field=models.CharField(
                choices=[("USER", "사용자"), ("ASSISTANT", "AI")],
                default="USER",
                help_text="USER(사용자) 또는 ASSISTANT(AI) 구분",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotsessions",
            name="using_model",
            field=models.CharField(
                choices=[
                    ("gemini-1.5-flash", "Gemini 1.5 Flash"),
                    ("gemini-2.0", "Gemini 2.0"),
                    ("gemini-2.5-flash", "Gemini 2.5 Flash"),
                ],
                help_text="LLM 사용 모델",
                max_length=50,
            ),
        ),
    ]
