# Generated by Django 5.2.8 on 2026-03-11 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatbotsessions",
            unique_together={("user", "question")},
        ),
        migrations.AddField(
            model_name="chatbotsessions",
            name="question",
            field=models.ForeignKey(
                blank=True,
                help_text="파생된 Q&A 질문 ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chatbot_sessions",
                to="questions.questions",
            ),
        ),
        migrations.RemoveField(
            model_name="chatbotsessions",
            name="questions",
        ),
    ]
