# Generated by Django 5.2.8 on 2026-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_rename_questions_chatbotsessions_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotsessions",
            name="using_model",
            field=models.CharField(
                choices=[
                    ("gemini-2.0-flash-lite-001", "Gemini 2 0 Flash Lite 001"),
                    ("gemini-2.0-flash", "Gemini 2.0 Flash"),
                    ("gemini-2.5-flash", "Gemini 2.5 Flash"),
                    ("gemini-2.5-flash-lite", "Gemini 2 5 Flash Lite"),
                ],
                help_text="LLM 사용 모델",
                max_length=50,
            ),
        ),
    ]
