# Generated by Django 5.2.8 on 2026-03-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_rename_questions_chatbotsessions_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotcompletions",
            name="role",
            field=models.CharField(
                choices=[("user", "사용자"), ("assistant", "AI")],
                default="user",
                help_text="USER(사용자) 또는 ASSISTANT(AI) 구분",
                max_length=10,
            ),
        ),
    ]
