# Generated by Django 5.2.8 on 2026-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_rename_questions_chatbotsessions_question_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatbotsessions",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="chatbotsessions",
            name="question",
        ),
        migrations.RemoveField(
            model_name="chatbotsessions",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatbotCompletions",
        ),
        migrations.DeleteModel(
            name="ChatbotSessions",
        ),
    ]
