# Generated by Django 5.2.8 on 2026-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=50)),
                ("thumbnail_img_url", models.CharField(default="default_img_url", max_length=255)),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ExamDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("duration_time", models.SmallIntegerField(default=60)),
                ("access_code", models.CharField(max_length=64)),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("questions_snapshot_json", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVEED", "Activeed"), ("DEACTIVATED", "Deactivated")],
                        default="Activated",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "exam_deployments",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("question", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("blank_count", models.SmallIntegerField(blank=True, null=True)),
                ("options_json", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("MULTIPLE_CHOICE", "Multiple Choice"), ("OX", "Ox"), ("FULL_BLANK", "Full Blank")],
                        max_length=20,
                    ),
                ),
                ("answer", models.JSONField()),
                ("point", models.SmallIntegerField()),
                ("explanation", models.TextField()),
            ],
            options={
                "db_table": "exam_questions",
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("started_at", models.DateTimeField()),
                ("cheating_count", models.SmallIntegerField()),
                ("answers_json", models.JSONField()),
                ("score", models.SmallIntegerField()),
                ("correct_answer_count", models.SmallIntegerField()),
            ],
            options={
                "db_table": "exam_submissions",
            },
        ),
    ]
