# Generated by Django 5.2.8 on 2026-03-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0001_initial"),
        ("subject", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="subject_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.subject"),
        ),
        migrations.AddField(
            model_name="examdeployment",
            name="cohort_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subject.cohort"),
        ),
        migrations.AddField(
            model_name="examdeployment",
            name="exam_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam.exam"),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exam_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam.exam"),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="deployment_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam.examdeployment"),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="submitter_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user"),
        ),
    ]
