# Generated by Django 5.2.8 on 2026-03-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_examdeployment_status_alter_examquestion_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="subject_id",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="examdeployment",
            old_name="cohort_id",
            new_name="cohort",
        ),
        migrations.RenameField(
            model_name="examdeployment",
            old_name="exam_id",
            new_name="exam",
        ),
        migrations.RenameField(
            model_name="examquestion",
            old_name="exam_id",
            new_name="exam",
        ),
        migrations.RenameField(
            model_name="examsubmission",
            old_name="deployment_id",
            new_name="deployment",
        ),
        migrations.RenameField(
            model_name="examsubmission",
            old_name="submitter_id",
            new_name="submitter",
        ),
    ]
