# Generated by Django 5.2.8 on 2026-03-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_rename_subject_id_exam_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="examdeployment",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="examdeployment",
            name="cohort",
        ),
        migrations.RemoveField(
            model_name="examsubmission",
            name="deployment",
        ),
        migrations.RemoveField(
            model_name="examsubmission",
            name="submitter",
        ),
        migrations.DeleteModel(
            name="ExamQuestion",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="ExamDeployment",
        ),
        migrations.DeleteModel(
            name="ExamSubmission",
        ),
    ]
