# Generated by Django 5.2.8 on 2026-03-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_rename_subject_id_exam_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examdeployment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVATED", "Activated"), ("DEACTIVATED", "Deactivated"), ("CLOSED", "Closed")],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("OX", "Ox"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("ORDERING", "Ordering"),
                    ("FULL_BLANK", "Full Blank"),
                ],
                default="SINGLE_CHOICE",
                max_length=20,
            ),
        ),
    ]
