# Generated by Django 5.2.8 on 2026-03-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_examdeployment_status_alter_examquestion_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExamQuestion",
        ),
    ]
