# Generated by Django 5.2.8 on 2026-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_examdeployment_status_alter_examquestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("OX", "Ox"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("ORDERING", "Ordering"),
                    ("FILL_BLANK", "Fill Blank"),
                ],
                default="SINGLE_CHOICE",
                max_length=20,
            ),
        ),
    ]
