# Generated by Django 5.2.8 on 2026-03-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="이메일")),
                ("hashed_password", models.CharField(max_length=130, verbose_name="비밀번호")),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("nickname", models.CharField(max_length=10, unique=True, verbose_name="닉네임")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="휴대폰번호")),
                ("gender", models.CharField(max_length=6, verbose_name="성별")),
                ("birthday", models.DateField(verbose_name="생년월일")),
                ("profile_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("U", "User"),
                            ("ST", "Student"),
                            ("TA", "Teaching Assistant"),
                            ("OM", "Operation Manager"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="User",
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=50)),
                ("provider_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="social_accounts", to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=50)),
                ("reason_detail", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
    ]
