# Generated by Django 5.2.8 on 2026-03-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="이메일")),
                ("hashed_password", models.CharField(max_length=130, verbose_name="비밀번호")),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("nickname", models.CharField(max_length=10, unique=True, verbose_name="닉네임")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="휴대폰번호")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=6, verbose_name="성별"
                    ),
                ),
                ("birthday", models.DateField(verbose_name="생년월일")),
                ("profile_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("STUDENT", "Student"),
                            ("TA", "Ta"),
                            ("OM", "Om"),
                            ("ADMIN", "Admin"),
                        ],
                        default="User",
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("provider", models.CharField(choices=[("kakao", "Kakao"), ("naver", "Naver")], max_length=10)),
                ("provider_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="social_accounts", to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("GRADUATION", "수강완료"),
                            ("TRANSFER", "타 부트캠프에 더 양질의 컨텐츠가 있어서"),
                            ("NO_LONGER_NEEDED", "더 이상 필요가 없어서"),
                            ("SERVICE_DISSATISFACTION", "사이트내 UX/UI가 불편해서"),
                            ("PRIVACY_CONCERN", "개인정보 우려 "),
                            ("OTHER", "기타(직접입력)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason_detail", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
    ]
