# Generated by Django 5.2.8 on 2026-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(choices=[("kakao", "KAKAO"), ("naver", "NAVER")], max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="reason",
            field=models.CharField(
                choices=[
                    ("GRADUATION", "수강완료"),
                    ("TRANSFER", "타 부트캠프에 더 양질의 컨텐츠가 있어서"),
                    ("NO_LONGER_NEEDED", "더 이상 필요가 없어서"),
                    ("SERVICE_DISSATISFACTION", "사이트내 UX/UI가 불편해서"),
                    ("PRIVACY_CONCERN", "개인정보 우려 "),
                    ("OTHER", "기타(직접입력)"),
                ],
                max_length=50,
            ),
        ),
    ]
