# Generated by Django 5.2.8 on 2026-03-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("ACTIVATED", "Activated"), ("DEACTIVATED", "Deactivated"), ("WITHDREW", "Withdrew")],
                default="ACTIVE",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("STUDENT", "Student"),
                    ("TA", "Ta"),
                    ("OM", "Om"),
                    ("LC", "Lc"),
                    ("ADMIN", "Admin"),
                ],
                default="USER",
                max_length=10,
                verbose_name="권한",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialuser",
            constraint=models.UniqueConstraint(fields=("user", "provider"), name="unique_social_account"),
        ),
    ]
