# Generated by Django 5.2.8 on 2026-03-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_socialuser_id_alter_socialuser_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("MALE", "남자"), ("FEMALE", "여자")], max_length=6, verbose_name="성별"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "일반 회원"),
                    ("STUDENT", "수강생"),
                    ("TA", "강사님"),
                    ("OM", "운영 매니저"),
                    ("ADMIN", "관리자"),
                ],
                default="User",
                max_length=10,
                verbose_name="역할",
            ),
        ),
    ]
