# Generated by Django 6.0.3 on 2026-03-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_hashed_password_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('WITHDREW', 'Withdrew')], default='ACTIVATED'),
        ),
    ]
