# Generated by Django 5.2.8 on 2026-03-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail_img_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.SmallIntegerField()),
                ("max_student", models.SmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(default="READY", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.course")),
            ],
        ),
        migrations.CreateModel(
            name="CohortStudent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cohort", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.cohort")),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("status", models.CharField(default="PENDING", max_length=10)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cohort", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.cohort")),
            ],
        ),
        migrations.CreateModel(
            name="LearningCoach",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.course")),
            ],
        ),
        migrations.CreateModel(
            name="OperationManager",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.course")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=30)),
                ("number_of_days", models.SmallIntegerField(blank=True, null=True)),
                ("number_of_hours", models.SmallIntegerField(blank=True, null=True)),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.course")),
            ],
        ),
        migrations.CreateModel(
            name="TrainingAssistant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cohort", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.cohort")),
            ],
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(fields=("course", "number"), name="uniq_cohort_course_number"),
        ),
        migrations.AddConstraint(
            model_name="cohortstudent",
            constraint=models.UniqueConstraint(fields=("cohort", "user_id"), name="uniq_cohort_student_user"),
        ),
        migrations.AddConstraint(
            model_name="enrollmentrequest",
            constraint=models.UniqueConstraint(fields=("cohort", "user_id"), name="uniq_enrollreq_cohort_user"),
        ),
        migrations.AddConstraint(
            model_name="learningcoach",
            constraint=models.UniqueConstraint(fields=("course", "user_id"), name="uniq_lcoach_course_user"),
        ),
        migrations.AddConstraint(
            model_name="operationmanager",
            constraint=models.UniqueConstraint(fields=("course", "user_id"), name="uniq_opmgr_course_user"),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("course", "title"), name="uniq_subject_course_title"),
        ),
        migrations.AddConstraint(
            model_name="trainingassistant",
            constraint=models.UniqueConstraint(fields=("cohort", "user_id"), name="uniq_ta_cohort_user"),
        ),
    ]
