# Generated by Django 5.2.8 on 2026-03-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0002_alter_course_thumbnail_img_url_cohort_cohortstudent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("thumbnail_img_url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.subject")),
            ],
        ),
        migrations.CreateModel(
            name="ExamDeployment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("duration_time", models.SmallIntegerField()),
                ("access_code", models.CharField(max_length=64, unique=True)),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("questions_snapshot_json", models.JSONField()),
                ("status", models.CharField(default="READY", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cohort", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.cohort")),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.exam")),
            ],
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("blank_count", models.SmallIntegerField(blank=True, null=True)),
                ("options_json", models.TextField(blank=True, null=True)),
                ("type", models.CharField(max_length=20)),
                ("answer", models.JSONField()),
                ("point", models.SmallIntegerField()),
                ("explanation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.exam")),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("submitter_id", models.BigIntegerField()),
                ("started_at", models.DateTimeField()),
                ("cheating_count", models.SmallIntegerField()),
                ("answers_json", models.JSONField()),
                (
                    "deployment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.examdeployment"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(fields=("subject", "title"), name="uniq_exam_subject_title"),
        ),
        migrations.AddConstraint(
            model_name="examsubmission",
            constraint=models.UniqueConstraint(
                fields=("deployment", "submitter_id"), name="uniq_submission_deploy_user"
            ),
        ),
    ]
