# Generated by Django 5.2.8 on 2026-03-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="ex) 전체게시판, 공지사항, 자유게시판, 일상 공유, 개발 지식 공유, 취업 정보 공유, 프로젝트 구인",
                        max_length=20,
                        verbose_name="카테고리 이름",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="T: 사용, F: 미사용", verbose_name="카테고리 사용 여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
            ],
            options={
                "verbose_name": "게시글 카테고리",
                "db_table": "post_category",
                "indexes": [models.Index(fields=["id"], name="pk_post_category")],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50, verbose_name="게시글 제목")),
                ("content", models.TextField(verbose_name="게시글 내용")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="게시글 조회수")),
                ("is_visible", models.BooleanField(default=True, verbose_name="게시글 활성화 여부")),
                ("is_notice", models.BooleanField(default=False, verbose_name="게시글 공지 활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="community.postcategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "db_table": "post",
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post", verbose_name="게시글id"
                    ),
                ),
            ],
            options={
                "db_table": "post_comment",
            },
        ),
        migrations.CreateModel(
            name="CommentTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.postcomment", verbose_name="댓글"
                    ),
                ),
            ],
            options={
                "db_table": "post_comment_tags",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("img_url", models.TextField(verbose_name="이미지 URL")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post", verbose_name="게시판id"
                    ),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지 목록",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "is_liked",
                    models.BooleanField(
                        default=False, help_text="T: 좋아요 활성화, F: 좋아요 비활성화", verbose_name="좋아요 여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="community.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 좋아요",
                "db_table": "post_like",
            },
        ),
        migrations.CreateModel(
            name="PostAttachments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_url", models.CharField(max_length=255, verbose_name="첨부파일 URL")),
                ("file_name", models.CharField(max_length=50, verbose_name="첨부파일 이름")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post", verbose_name="게시판id"
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일 목록",
                "indexes": [models.Index(fields=["post"], name="idx_post_attachments_post_id")],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["id"], name="post_id_1bcbbb_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="post_created_120ba3_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["category"], name="post_categor_4e0ece_idx"),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["post", "created_at"], name="idx_post_id_created_at"),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(fields=["post"], name="idx_post_images_post_id"),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(fields=["post_id"], name="idx_post_like_id"),
        ),
    ]
