# Generated by Django 5.2.8 on 2026-03-10 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "name",
                    models.CharField(
                        help_text="ex) 전체게시판, 공지사항, 자유게시판, 일상 공유, 개발 지식 공유, 취업 정보 공유, 프로젝트 구인",
                        max_length=20,
                        verbose_name="카테고리 이름",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="T: 사용, F: 미사용", verbose_name="카테고리 사용 여부"
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 카테고리",
                "db_table": "post_categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=50, verbose_name="게시글 제목")),
                ("content", models.TextField(verbose_name="게시글 내용")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="게시글 조회수")),
                ("is_visible", models.BooleanField(default=True, verbose_name="게시글 활성화 여부")),
                ("is_notice", models.BooleanField(default=False, verbose_name="게시글 공지 활성화 여부")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="users.user",
                        verbose_name="작성자",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="community.postcategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("content", models.CharField(max_length=300)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user", verbose_name="작성자id"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post", verbose_name="게시글id"
                    ),
                ),
            ],
            options={
                "db_table": "post_comments",
            },
        ),
        migrations.CreateModel(
            name="CommentTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "tagged_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user", verbose_name="태그된 ID"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.postcomment", verbose_name="댓글"
                    ),
                ),
            ],
            options={
                "db_table": "post_comment_tags",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("img_url", models.TextField(verbose_name="이미지 URL")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post", verbose_name="게시판id"
                    ),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지 목록",
                "db_table": "post_images",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "is_liked",
                    models.BooleanField(
                        default=True, help_text="T: 좋아요 활성화, F: 좋아요 비활성화", verbose_name="좋아요 여부"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="community.post",
                        verbose_name="게시글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="users.user",
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 좋아요",
                "db_table": "post_likes",
            },
        ),
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_url", models.CharField(max_length=255, verbose_name="첨부파일 URL")),
                ("file_name", models.CharField(max_length=50, verbose_name="첨부파일 이름")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post", verbose_name="게시판id"
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일 목록",
                "db_table": "post_attachments",
                "indexes": [models.Index(fields=["post"], name="idx_post_attachments_post_id")],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author"], name="posts_author__aaae70_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_created_060265_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["category"], name="posts_categor_e255e1_idx"),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["post", "created_at"], name="idx_post_id_created_at"),
        ),
        migrations.AddIndex(
            model_name="commenttag",
            index=models.Index(fields=["tagged_user"], name="idx_tagged_user_id"),
        ),
        migrations.AddConstraint(
            model_name="commenttag",
            constraint=models.UniqueConstraint(fields=("comment", "tagged_user"), name="unique_comment_tagged_user"),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(fields=["post"], name="idx_post_images_post_id"),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(fields=["post_id"], name="idx_post_like_id"),
        ),
    ]
