# Generated by Django 5.2.8 on 2026-03-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commenttag",
            options={"verbose_name_plural": "댓글 태그"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "게시글"},
        ),
        migrations.AlterModelOptions(
            name="postcategory",
            options={"verbose_name": "게시글 카테고리", "verbose_name_plural": "게시글 카테고리"},
        ),
        migrations.AlterModelOptions(
            name="postcomment",
            options={"verbose_name_plural": "게시글 댓글"},
        ),
        migrations.AlterModelOptions(
            name="postlike",
            options={"verbose_name": "게시글 좋아요", "verbose_name_plural": "게시글 좋아요"},
        ),
    ]
