# Generated by Django 5.2.8 on 2026-03-23 08:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_commenttag_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="postcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_post_category_name"
            ),
        ),
    ]
